/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pt.up.fe.sdis2021.t7g10.lab4.server;

import org.junit.jupiter.api.Test;

public class LinkedListTest {
    @Test public void testConstructor() {
        App list = new App();
        assertEquals(0, list.size());
    }

    @Test public void testAdd() {
        App list = new App();

        list.add("one");
        assertEquals(1, list.size());
        assertEquals("one", list.get(0));

        list.add("two");
        assertEquals(2, list.size());
        assertEquals("two", list.get(1));
    }

    @Test public void testRemove() {
        App list = new App();

        list.add("one");
        list.add("two");
        assertTrue(list.remove("one"));

        assertEquals(1, list.size());
        assertEquals("two", list.get(0));

        assertTrue(list.remove("two"));
        assertEquals(0, list.size());
    }

    @Test public void testRemoveMissing() {
        App list = new App();

        list.add("one");
        list.add("two");
        assertFalse(list.remove("three"));
        assertEquals(2, list.size());
    }
}
