/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pt.up.fe.sdis2021.t7g10.client;

import pt.up.fe.sdis2021.t7g10.server.LinkedList;

import static pt.up.fe.sdis2021.t7g10.utilities.StringUtils.join;
import static pt.up.fe.sdis2021.t7g10.utilities.StringUtils.split;
import static pt.up.fe.sdis2021.t7g10.client.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
